export const workingHours = { monday:[{start:'09:00',end:'17:00'}], tuesday:[{start:'09:00',end:'17:00'}], wednesday:[{start:'09:00',end:'17:00'}], thursday:[{start:'09:00',end:'17:00'}], friday:[{start:'09:00',end:'17:00'}], saturday:[], sunday:[] };
export const tradeTemplates = [
 { tradeType:'Electrician', services:[['EICR certificate','fixed_price',120,['postcode','property type','preferred date'],['regulated_trade','electrical_safety']],['Add socket','fixed_price',95,['postcode','property type','photos optional'],['regulated_trade']],['Fault finding call-out','callout_plus_hourly',80,['postcode','issue description','urgency'],['electrical_safety']]]},
 { tradeType:'Gas engineer', services:[['Boiler service','fixed_price',85,['postcode','boiler make/model','preferred date'],['regulated_trade','gas_safety','no_unsafe_advice']],['Gas safety certificate','fixed_price',75,['postcode','certificate type','preferred date'],['regulated_trade','gas_safety']],['Boiler breakdown visit','callout_plus_hourly',95,['postcode','boiler make/model','issue description','urgency'],['gas_safety']]]},
 { tradeType:'Roofer', services:[['Leak inspection','from_price',120,['postcode','photos','property type','access notes'],['working_at_height','weather_dependent']],['Gutter repair','quote_after_photos',0,['postcode','photos','access notes'],['working_at_height']]]},
 { tradeType:'Mobile detailer', services:[['Deep clean','package_price',140,['postcode','vehicle size','vehicle condition','water/power access'],['access_required','weather_dependent']],['Maintenance wash','package_price',60,['postcode','vehicle size'],['weather_dependent']]]},
 { tradeType:'Cleaner', services:[['End-of-tenancy clean','package_price',160,['postcode','property size','rooms','preferred date'],[]],['Oven clean','fixed_price',65,['postcode','preferred date'],[]]]},
 { tradeType:'Plumber', services:[['Leak visit','callout_plus_hourly',90,['postcode','issue description','urgency','water isolation status'],['emergency','water_damage','safety_triage']],['Tap replacement','fixed_price',85,['postcode','photos optional','preferred date'],[]]]},
 { tradeType:'Window tinting', services:[['Rear window tints','fixed_price',150,['postcode','vehicle make/model','shade preference','preferred date'],[]],['Full vehicle tint','from_price',220,['postcode','vehicle make/model','shade preference'],[]]]}
] as const;
export const demoMessages = ['Hi, need an EICR for a 3 bed house in Stafford next week. How much?','Hi mate, how much for a Worcester boiler service? I’m in Cannock and can do Friday.','I’ve got a leak coming through the bedroom ceiling when it rains. Can you come out? I’m in Walsall.','How much for a deep clean on a Range Rover? It’s pretty dirty inside. Based in Wolverhampton.','Need an end of tenancy clean for a 2 bed flat in Birmingham next Thursday.','How much for rear tints on a Golf? I’m in Cannock and can do Friday.'];
