import type { PricingResult } from '@/lib/types';
type Svc = { requiredFields?: unknown; pricingStrategy: string; autoQuoteAllowed?: boolean }; type Rule = { pricingStrategy: string; basePrice?: number|null; fromPrice?: number|null; hourlyRate?: number|null; calloutFee?: number|null; currency?: string; modifiers?: unknown; active?: boolean };
const val = (vars: Record<string, any>, field: string) => field === 'urgency' ? vars.urgency : vars[field];
function missing(required: unknown, vars: Record<string, any>) { return Array.isArray(required) ? required.filter(f => typeof f === 'string' && !f.includes('optional') && !vars[f] && !(f === 'postcode' && vars.postcode)) : []; }
function applyModifiers(price: number, modifiers: unknown, vars: Record<string, any>) { let owner = false; if (!Array.isArray(modifiers)) return { price, owner }; for (const m of modifiers as any[]) { const actual = val(vars, m.field); const match = (m.equals !== undefined && actual === m.equals) || (m.gt !== undefined && Number(actual) > Number(m.gt)) || (m.lt !== undefined && Number(actual) < Number(m.lt)) || (m.exists && actual !== undefined); if (!match) continue; if (m.action === 'owner_required') owner = true; if (typeof m.add === 'number') price += m.add; if (typeof m.multiplyBy === 'number') price += Number(actual ?? 0) * m.multiplyBy; } return { price, owner }; }
export function priceLead(input: { business?: { defaultCurrency?: string }; service: Svc; priceRules: Rule[]; jobVariables?: Record<string, any>; urgency?: string; distanceMiles?: number }): PricingResult { const rule = input.priceRules.find(r => r.active !== false) ?? input.priceRules[0]; const currency = rule?.currency ?? input.business?.defaultCurrency ?? 'GBP'; const vars = { ...(input.jobVariables ?? {}), urgency: input.urgency, distance_miles: input.distanceMiles, postcode: (input.jobVariables ?? {}).postcode }; const miss = missing(input.service.requiredFields, vars); const strategy = rule?.pricingStrategy ?? input.service.pricingStrategy; if (!rule || strategy === 'owner_required') return { canQuote:false,currency,confidence:0.2,priceType:'manual',explanation:'Owner review is required by pricing rules.',missingFields:miss,requiresOwnerApproval:true };
 if (strategy === 'quote_after_photos') return { canQuote:false,currency,confidence:0.4,priceType:'manual',explanation:'Photos/details are required before quoting.',missingFields:[...new Set([...miss,'photos'])],requiresOwnerApproval:true };
 if (strategy === 'from_price') return { canQuote:true,fromPrice:Number(rule.fromPrice ?? rule.basePrice ?? 0),currency,confidence:0.78,priceType:'from',explanation:`From ${currency} ${rule.fromPrice ?? rule.basePrice}; confirm details before final price.`,missingFields:miss,requiresOwnerApproval:miss.length>0 };
 if (strategy === 'callout_plus_hourly') return { canQuote:true,price:Number(rule.calloutFee ?? 0),currency,confidence:0.82,priceType:'estimate',explanation:`Call-out ${currency} ${rule.calloutFee ?? 0}, then ${currency} ${rule.hourlyRate ?? 0}/hour if needed.`,missingFields:miss,requiresOwnerApproval:miss.length>0 };
 if (miss.length) return { canQuote:false,currency,confidence:0.5,priceType:'manual',explanation:'Required fields are missing.',missingFields:miss,requiresOwnerApproval:true };
 const base = Number(rule.basePrice ?? rule.fromPrice ?? 0); const applied = applyModifiers(base, rule.modifiers, vars); return { canQuote:!applied.owner,price:applied.price,currency,confidence:applied.owner ? 0.55 : 0.94,priceType:strategy === 'package_price' ? 'estimate' : 'fixed',explanation: applied.owner ? 'A modifier requires owner review.' : 'Calculated from saved pricing rules.',missingFields:[],requiresOwnerApproval:applied.owner || input.service.autoQuoteAllowed === false } }
