import assert from 'node:assert/strict';
function priceLead({service,priceRules,jobVariables={},urgency,distanceMiles}){const r=priceRules[0];let price=r.basePrice??r.fromPrice??0;let owner=false;for(const m of r.modifiers??[]){const actual=m.field==='urgency'?urgency:m.field==='distance_miles'?distanceMiles:jobVariables[m.field];const match=(m.equals!==undefined&&actual===m.equals)||(m.gt!==undefined&&Number(actual)>m.gt);if(match){if(m.add)price+=m.add;if(m.multiplyBy)price+=Number(actual||0)*m.multiplyBy;if(m.action==='owner_required')owner=true;}} if(r.pricingStrategy==='quote_after_photos')return{canQuote:false,missingFields:['photos']}; return{canQuote:!owner,price,requiresOwnerApproval:owner||service.autoQuoteAllowed===false};}
assert.equal(priceLead({service:{autoQuoteAllowed:true},priceRules:[{pricingStrategy:'fixed_price',basePrice:85}],jobVariables:{postcode:'ST16'}}).price,85);
assert.equal(priceLead({service:{autoQuoteAllowed:true},priceRules:[{pricingStrategy:'package_price',basePrice:140,modifiers:[{field:'vehicle_size',equals:'large',add:30}]}],jobVariables:{vehicle_size:'large'}}).price,170);
assert.equal(priceLead({service:{autoQuoteAllowed:true},priceRules:[{pricingStrategy:'fixed_price',basePrice:85,modifiers:[{field:'distance_miles',gt:25,action:'owner_required'}]}],distanceMiles:30}).canQuote,false);
assert.equal(priceLead({service:{autoQuoteAllowed:true},priceRules:[{pricingStrategy:'quote_after_photos'}]}).canQuote,false);
assert.equal(priceLead({service:{autoQuoteAllowed:true},priceRules:[{pricingStrategy:'fixed_price',basePrice:90,modifiers:[{field:'urgency',equals:'emergency',add:50}]}],urgency:'emergency'}).price,140);
const policy=(a,mode='autopilot')=>!(mode==='draft_only'||a.confidence<.75||['complaint','unknown','personal','supplier','spam'].includes(a.classification)||(a.riskFlags||[]).length);
assert.equal(policy({classification:'complaint',confidence:.9,riskFlags:[]}),false); assert.equal(policy({classification:'new_lead',confidence:.5,riskFlags:[]}),false); assert.equal(policy({classification:'new_lead',confidence:.9,riskFlags:[]}),true); assert.equal(policy({classification:'supplier',confidence:.9,riskFlags:[]}),false);
const overlap=(a,b)=>a.start<b.end&&b.start<a.end; assert.equal(overlap({start:new Date(0),end:new Date(10)},{start:new Date(5),end:new Date(15)}),true); assert.equal(overlap({start:new Date(0),end:new Date(10)},{start:new Date(10),end:new Date(15)}),false);
const key=p=>p.filter(Boolean).join(':'); assert.equal(key(['biz','wa','1']),key(['biz','wa','1'])); assert.notEqual(key(['biz','wa','1']),key(['biz','wa','2']));
console.log('all tests passed');
